# Generated by Django 2.1.7 on 2019-03-30 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emaiiil', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FirstName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fir_name', models.CharField(max_length=264, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LastName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('las_name', models.CharField(max_length=264, unique=True)),
                ('f_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djtwo_app.FirstName')),
            ],
        ),
        migrations.AddField(
            model_name='email',
            name='emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djtwo_app.LastName'),
        ),
    ]
