# Generated by Django 2.1.7 on 2019-03-31 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djtwo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=264)),
                ('last_name', models.CharField(max_length=264)),
                ('email', models.EmailField(max_length=264, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='email',
            name='emp',
        ),
        migrations.RemoveField(
            model_name='lastname',
            name='f_name',
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='FirstName',
        ),
        migrations.DeleteModel(
            name='LastName',
        ),
    ]
